# 快手视频刷金币测试，抓包获取secrets

name: 腾讯新闻自动阅读

on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 2,8,16 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        TX_CK: ${{ secrets.TX_CK }}
        TX_CK2: ${{ secrets.TX_CK2 }}
        TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【腾讯新闻自动阅读一】'
        if: secrets.TX_CK
        run: |
          node Task/txnews_task.js
        env:
          TX_CK: ${{ secrets.TX_CK }}
          TX_READ: ${{ secrets.TX_READ }}
          TX_VIDEO: ${{ secrets.TX_VIDEO }}
          
      - name: '运行 【腾讯新闻自动阅读二】'
        if: env.TX_CK2
        run: |
          node Task/txnews_task.js
        env:
          TX_CK: ${{ secrets.TX_CK2 }}
          TX_READ: ${{ secrets.TX_READ }}
          TX_VIDEO: ${{ secrets.TX_VIDEO }}
          
        env:      
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
